export const profiles = {
  m1: {
    called: "Marcus",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
  d2: {
    called: "Branch",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
  n3: {
    called: "Notch MacClusky",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
  j4: {
    called: "Tripp",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
  d5: {
    called: "Daniel",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
  d6: {
    called: "Sparky Pinciotti",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
  s7: {
    called: "Sage",
    message: "hi guys!",
    voteA: "",
    voteB: "",
    voteC: "",
    voteD: "",
    pic: "",
  },
};
